### ISSUE TITLE
Graphviz Install Broken

### ISSUE THREAD

**Issue by mjcarroll** [wjwwood/ros-osx#4]
Graphviz --with-pdf install through rosdep is broken.

Libiconv breaks it.

https://github.com/mxcl/homebrew/issues/7463

Yup.

**Comment by wjwwood** [comment]
https://github.com/mxcl/homebrew/issues/7140

Also.

**Comment by mjcarroll** [comment]
7140 fixes it.  I think it's a matter of upstream adoption now.

**Comment by mjcarroll** [comment]
https://gist.github.com/1202508

**Comment by wjwwood** [comment]
Fixed upstream.
