### ISSUE TITLE
pyCairo segmentation fault 11 when starting rxgraph

### ISSUE THREAD

**Issue by mjcarroll** [wjwwood/ros-osx#5]
I did some basic fixes to rxgraph, but it seems that there is a deeper underlying problem with cairo.

I get segmentation fault: 11

Full apple crash log: https://gist.github.com/956d268748c04cbd3731

**Comment by wjwwood** [comment]
rxgraph is getting reimplemented.

ashgti's set of gtk related formulas fix this in the mean time: https://github.com/mxcl/homebrew/pull/7658
