### ISSUE TITLE
IndexError in apply-patches.py due to delete_empty.sh

### ISSUE THREAD

**Issue by bpartridge** [wjwwood/ros-osx#7]
In a recent commit, patches/delete_empty.sh was added. However, this is scanned by apply-patches.sh, and since it doesn't follow the filename pattern of the other patches, it throws an IndexError. Fixed by removing delete_empty.sh. Reproduced on two separate Lion installations, including a brand new machine.

Traceback (most recent call last):
  File "apply-patches.py", line 67, in <module>
    if len(patch_info) != 4 and patch_info[2] != "homebrew" and patch_info[3].split('.')[0] not in ["svn", "git", "hg"]:
IndexError: list index out of range

**Comment by bpartridge** [comment]
My hypothesis is that the "if and and" logic should be "if or or", so that it exits immediately, right?

**Comment by wjwwood** [comment]
This is a bug, I will push a commit soon.  

Just FYI, the majority of my patches are now in ros branches, if not in the latest tagged versions.  You can see the integration progress here: http://www.ros.org/wiki/fuerte/Planning/OSX

I appreciate your interest in helping me fix/maintain this stuff, but I am hoping that within a week or so all of this will be unnecessary.
