### ISSUE TITLE
os_detect.py always detects Osx instead of OsxBrew

### ISSUE THREAD

**Issue by bpartridge** [wjwwood/ros-osx#8]
There doesn't seem to be any patch for the Osx and OsxBrew classes in os_detect.py in roslib/src/roslib/os_detect.py, and so they are using the default behavior of:

```
class OsxBrew(OSBase):
    """
    Detect OS X 
    """

    def check_presence(self):
        # not enabled for ROS Electric.  Only enabled under override.
        return False
```

Therefore, any rosdep operation fails with being unable to find Macports, since the OS is being detected as Osx instead of Osxbrew. This occurs on a brand-new Lion computer, as well as a computer with Macports installed and then completely removed (/opt removed). IMHO if there was ever a reason for having custom patches in this repository, this would be it.

**Comment by wjwwood** [comment]
My patches for the ros and ros_comm stacks are out-of-date, you shouldn't need any of them.

If you want to use Homebrew on OSX simply do `export ROS_OS_OVERRIDE=osxbrew:lion`.

Sorry to have wasted your time, I will update the instructions asap.  I was waiting until all the changes had been merged, but I will put up a message now on the instructions.
